---

- name: MY FIRST PLAYBOOK
  hosts: R1
  gather_facts: false
  connection: network_cli

  tasks:
    - name: run show version on remote devices
      cisco.ios.ios_command:
        commands: show version
      register: my_output

    - debug: var=my_output
